# Generated by Django 3.0.2 on 2020-02-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Name')),
                ('opentime', models.TimeField(blank=True)),
                ('closetime', models.TimeField(blank=True)),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='City')),
                ('address', models.TextField(blank=True, max_length=200)),
                ('services', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
