# Generated by Django 3.0.2 on 2020-02-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200225_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
