# Generated by Django 3.0.2 on 2020-02-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200225_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.ImageField(null=True, upload_to='gym_image'),
        ),
    ]
