# Generated by Django 3.0.2 on 2020-02-05 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20200205_1143'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('1', '10 A.M To 12 P.M'), ('2', '12 P.M To 2 P.M'), ('3', ' 2 P.M To 4 P.M'), ('4', ' 4 P.M To 6 P.M'), ('5', ' 6 P.M To 8 P.M')], default='1', max_length=50)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.City')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Cleaner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
