# Generated by Django 3.0.2 on 2020-02-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200206_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='City',
            new_name='city',
        ),
    ]
