# Generated by Django 3.0.2 on 2020-02-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_charecter_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='charecter',
            name='movies',
            field=models.ManyToManyField(to='accounts.Movie'),
        ),
    ]
